import Head from "next/head";
import { Header, Filter } from "@/components";
import { Container } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>iJOBS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container maxW="5xl" pt="5">
        <Filter
          {...{ availabilities, workingModels, specialties, locations }}
          receivedFilterValues={(values) => console.log(values)}
        />
      </Container>
    </>
  );
}
const workingModels = ["Home office", "Híbrido", "Presencial"];

const availabilities = ["Freelance", "Full Time", "PJ", "CLT"];

const specialties = [
  "Frontend",
  "Backend",
  "Mobile",
  "Full stack",
  "UI Designer",
  "UX Designer",
];

const locations = [
  {
    id: "any_id_1",
    name: "Goiânia",
  },
  {
    id: "any_id_2",
    name: "São Paulo",
  },
  {
    id: "any_id_3",
    name: "Rio de Janeiro",
  },
  {
    id: "any_id_4",
    name: "Florianópolis",
  },
  {
    id: "any_id_5",
    name: "Chapecó",
  },
];
